### PR TITLE
Missing return statement

### PR DESCRIPTION
**Pull request by igl**
You forgot the return statement...  I also updated the README with real examples.

### CODE REVIEW

**Comment by igl** [comment]
:(

**Comment by igl** [comment]
@krilo pretty plz
I NEED this lib!

**Review by krilo — APPROVED** [review]

**Comment by krilo** [comment]
Haha yea good stuff, thanks :)

**Comment by igl** [comment]
w00p w00p. Now bump that version and publish... See if the we can get that dependents count up!

**Pull request merged**
